INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('93','AFGHANISTAN','KABUL','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('355','ALBANIA','TIRANE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('213','ALGERIA','ALGIERS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('376','ANDORRA','ANDORRA LA VELLA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('244','ANGOLA','LUANDA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('102','ANTIGUA','ST. JOHN''S','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('54','ARGENTINA','BUENOS AIRES','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('374','ARMENIA','YEREVAN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('61','AUSTRALIA','CANBERRA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('43','AUSTRIA','VIENNA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('994','AZERBAIJAN','BAKU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('103','BAHAMAS','NASSAU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('973','BAHRAIN','MANAMA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('880','BANGLADESH','DHAKA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('104','BARBADOS','BRIDGETOWN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('120','BARBUDA','CODRINGTON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('375','BELARUS','MINSK','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('32','BELGIUM','BRUSSELS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('501','BELIZE','BELMOPAN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('229','BENIN','COTONOU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('975','BHUTAN','THIMPHU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('591','BOLIVIA','SUCRE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('387','BOSNIA - HERZEGOVINA','SARAJEVO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('267','BOTSWANA','GABORONE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('55','BRAZIL','BRASILIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('673','BRUNEI','BANDAR SERI BEGAWAN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('359','BULGARIA','SOFIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('226','BURKINA FASO','OUAGADOUGOU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('257','BURUNDI','BUJUMBURA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('855','CAMBODIA','PHNOM PENH','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('237','CAMEROON','YAOUNDE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('11','CANADA','OTTAWA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('238','CAPE VERDE ISLANDS','PRAIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('236','CENTRAL AFRICAN REP.','BANGUI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('235','CHAD','N''DJAMENA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('56','CHILE, REP. OF','SANTIAGO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('86','CHINA','BEIJING','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('57','COLOMBIA','BOGOTA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('269','COMOROS','MORONI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('242','CONGO, REP. OF THE','BRAZZAVILLE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('506','COSTA RICA','SAN JOSE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('385','CROATIA','ZAGREB','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('53','CUBA','HAVANA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('357','CYPRUS','NICOSIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('420','CZECH REP.','PRAGUE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('45','DENMARK','COPENHAGEN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('253','DJIBOUTI','DJIBOUTI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('109','DOMINICA','ROSEAU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('110','DOMINICAN REP.','SANTO DOMINGO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('593','ECUADOR','QUITO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('20','EGYPT','CAIRO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('503','EL SALVADOR','SAN SALVADOR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('44','UNITED KINGDOM','LONDON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('240','EQUATORIAL GUINEA','MALABO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('291','ERITREA','ASMARA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('372','ESTONIA','TALLINN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('251','ETHIOPIA','ADDIS ABABA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('679','FIJI','SUVA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('358','FINLAND','HELSINKI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('33','FRANCE','PARIS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('241','GABON','LIBREVILLE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('220','GAMBIA','BANJUL','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('995','GEORGIA','TBILISI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('49','GERMANY','BERLIN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('233','GHANA','ACCRA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('30','GREECE','ATHENS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('111','GRENADA ST.','GEORGE''S','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('502','GUATEMALA','GUATEMALA CITY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('224','GUINEA','CONAKRY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('245','GUINEA-BISSAU','BISSAU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('592','GUYANA','GEORGETOWN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('509','HAITI','PORT-AU-PRINCE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('504','HONDURAS','TEGUCIGALPA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('852','HONG KONG','HONG KONG','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('36','HUNGARY','BUDAPEST','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('354','ICELAND','REYKJAVIK','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('91','INDIA','NEW DELHI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('62','INDONESIA','JAKARTA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('98','IRAN, ISLAMIC REP. OF','TEHERAN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('964','IRAQ','BAGHDAD','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('353','IRELAND','DUBLIN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('972','ISRAEL','JERUSALEM','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('39','ITALY','ROME','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('112','JAMAICA','KINGSTON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('81','JAPAN','TOKYO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('962','JORDAN','AMMAN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('7','KAZAKHSTAN','ASTANA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('254','KENYA','NAIROBI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('686','KIRIBATI','TARAWA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('850','KOREA, NORTH','PYONGYANG','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('82','KOREA, SOUTH','SEOUL','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('965','KUWAIT','KUWAIT CITY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('71','KYRGYZSTAN','BISHKEK','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('856','LAOS','VIENTIANE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('371','LATVIA','RIGA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('961','LEBANON','BEIRUT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('266','LESOTHO','MASERU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('231','LIBERIA','MONROVIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('218','LIBYAN ARAB JAMAHIRIYA','TRIPOLI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('411','LIECHTENSTEIN','VADUZ','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('370','LITHUANIA','VILNIUS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('352','LUXEMBOURG','LUXEMBOURG','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('389','MACEDONIA (F.Y.R.O.M.)','SKOPJE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('261','MADAGASCAR','ANTANANARIVO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('265','MALAWI','LILONGWE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('60','MALAYSIA','KUALA LUMPUR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('960','MALDIVES','MALE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('223','MALI','BAMAKO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('356','MALTA','VALLETTA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('692','MARSHALL ISLANDS','MAJURO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('222','MAURITANIA','NOUAKCHOTT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('230','MAURITIUS','PORT LOUIS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('52','MEXICO','MEXICO CITY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('691','MICRONESIA, FEDERATED STATES OF','PALIKIR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('373','MOLDOVA, REP. OF','CHISINAU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('377','MONACO','MONACO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('976','MONGOLIA','ULAN BATOR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('212','MOROCCO','RABAT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('258','MOZAMBIQUE','MAPUTO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('95','MYANMAR','RANGOON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('264','NAMIBIA','WINDHOEK','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('674','NAURU','YAREN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('977','NEPAL','KATHMANDU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('31','NETHERLANDS','THE HAGUE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('599','NETHERLANDS ANTILLES','AMSTERDAM','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('64','NEW ZEALAND','WELLINGTON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('505','NICARAGUA','MANAGUA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('227','NIGER','NIAMEY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('234','NIGERIA','ABUJA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('47','NORWAY','OSLO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('968','OMAN','MUSCAT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('92','PAKISTAN','ISLAMABAD','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('680','PALAU','KOROR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('507','PANAMA','PANAMA CITY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('675','PAPUA NEW GUINEA','PORT MORESBY','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('595','PARAGUAY','ASUNCION','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('51','PERU','LIMA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('63','PHILIPPINES','MANILA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('48','POLAND','WARSAW','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('351','PORTUGAL','LISBON','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('974','QATAR','DOHA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('40','ROMANIA','BUCHAREST','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('72','RUSSIA','MOSCOW','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('250','RWANDA','KIGALI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('378','SAN MARINO','SAN MARINO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('239','SAO TOME & PRINCIPE','SAO TOME','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('966','SAUDI ARABIA','RIYADH','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('442','SCOTLAND','EDINBURGH','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('221','SENEGAL','DAKAR','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('248','SEYCHELLES','VICTORIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('232','SIERRA LEONE','FREETOWN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('65','SINGAPORE','SINGAPORE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('421','SLOVAKIA','BRATISLAVA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('386','SLOVENIA','LJUBLJANA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('677','SOLOMON ISLANDS','HONIARA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('252','SOMALIA','MOGADISHU','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('27','SOUTH AFRICA','CAPE TOWN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('34','SPAIN','MADRID','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('94','SRI LANKA','SRI JAYAWARDENEPURA KOTTE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('249','SUDAN','KHARTOUM','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('597','SURINAME','PARAMARIBO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('268','SWAZILAND','MBABANE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('46','SWEDEN','STOCKHOLM','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('41','SWITZERLAND','BERN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('963','SYRIAN ARAB REP.','DAMASCUS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('886','TAIWAN','TAIPEI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('708','TAJIKISTAN','DUSHANBE','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('255','TANZANIA','DODOMA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('66','THAILAND','BANGKOK','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('228','TOGO','LOME','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('676','TONGA','NUKU''ALOFA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('117','TRINIDAD & TOBAGO','PORT-OF-SPAIN','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('216','TUNISIA','TUNIS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('90','TURKEY','ANKARA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('709','TURKMENISTAN','ASHGABAT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('688','TUVALU','FUNAFUTI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('256','UGANDA','KAMPALA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('380','UKRAINE','KIEV','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('971','UNITED ARAB EMIRATES','ABU DHABI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('598','URUGUAY','MONTEVIDEO','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('1','USA','WASHINGTON, DC','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('711','UZBEKISTAN','TASHKENT','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('678','VANUATU','PORT VILA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('58','VENEZUELA','CARACAS','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('84','VIETNAM','HANOI','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('441','WALES','CARDIFF','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('685','WESTERN SAMOA','APIA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('967','YEMEN','SANA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('260','ZAMBIA','LUSAKA','admin',CURRENT_TIMESTAMP);
INSERT INTO com_nation(nation_cd,nation_nm,capital,created_by,created_at) VALUES('263','ZIMBABWE','HARARE','admin',CURRENT_TIMESTAMP);